-- Define Test Table

CREATE TABLE TEST.EMP (
  ID CHAR(10),
  NAME VARCHAR2(50),
  CREATED_DATE DATE,
  PRIMARY KEY(ID)
);

CREATE TABLE TEST.CUSTOMER (
  ID CHAR(10),
  NAME VARCHAR2(50),
  PRIMARY KEY(ID)
);

CREATE TABLE TEST.CUSTOMER_COMMENT (
  ID        NUMBER(10),
  CUSTOMER_ID CHAR(10),
  PRIMARY KEY(ID)
);

-- Test Data

INSERT INTO TEST.EMP (ID, NAME, CREATED_DATE) VALUES ('1', 'EMP1', '2016-01-23');
INSERT INTO TEST.EMP (ID, NAME, CREATED_DATE) VALUES ('2', 'EMP2', '2016-01-23');
INSERT INTO TEST.EMP (ID, NAME, CREATED_DATE) VALUES ('3', 'EMP3', '2016-01-23');

INSERT INTO TEST.CUSTOMER (ID, NAME) VALUES ('1', 'CUSTOMER1');
INSERT INTO TEST.CUSTOMER (ID, NAME) VALUES ('2', 'CUSTOMER2');
INSERT INTO TEST.CUSTOMER (ID, NAME) VALUES ('3', 'CUSTOMER3');

